### ISSUE TITLE
Issues when trying to run it in Spark

### ISSUE THREAD

**Issue by edgararuiz-zz** [WinVector/cdata#2]
Hi, I just tried using the example by switching it to Spark, and it doesn't seem to work. Here's the `reprex`: 

``` r
library("cdata")
#> Warning: package 'cdata' was built under R version 3.5.2
library("rquery")
#> Warning: package 'rquery' was built under R version 3.5.2

use_spark <- TRUE

if(use_spark) {
  my_db <- sparklyr::spark_connect(master = "local")
} else {
  my_db <- DBI::dbConnect(RSQLite::SQLite(),
                          ":memory:")
}



# pivot example
d <- wrapr::build_frame(
  "meas", "val" |
    "AUC" , 0.6   |
    "R2"  , 0.2   )
DBI::dbWriteTable(my_db,
                  'd',
                  d,
                  temporary = TRUE)
rstr(my_db, 'd')
#> table `d` spark_connection spark_shell_connection DBIConnection 
#>  nrow: 2 
#> 'data.frame':    2 obs. of  2 variables:
#>  $ meas: chr  "AUC" "R2"
#>  $ val : num  0.6 0.2
#  table `d` SQLiteConnection 
#   nrow: 2 
#  'data.frame':   2 obs. of  2 variables:
#   $ meas: chr  "AUC" "R2"
#   $ val : num  0.6 0.2
td <- db_td(my_db, "d")
td
#> [1] "table(`d`; meas, val)"
#  [1] "table(`d`; meas, val)"

cT <- td %.>%
  build_pivot_control(.,
                      columnToTakeKeysFrom= 'meas',
                      columnToTakeValuesFrom= 'val') %.>%
  execute(my_db, .)
#> Error: org.apache.spark.sql.AnalysisException: Hive support is required to CREATE Hive TABLE (AS SELECT);;
#> 'CreateTable `bpc_48623774849800522553_0000000000`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, ErrorIfExists
#> +- Project [meas#9, val#10]
#>    +- SubqueryAlias d
#>       +- LogicalRDD [meas#9, val#10], false
#> 
#>  at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$$anonfun$apply$12.apply(rules.scala:384)
#>  at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$$anonfun$apply$12.apply(rules.scala:382)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:117)
#>  at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$.apply(rules.scala:382)
#>  at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$.apply(rules.scala:380)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$2.apply(CheckAnalysis.scala:349)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$2.apply(CheckAnalysis.scala:349)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:349)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:91)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:104)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
#>  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:74)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:638)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#>  at java.lang.reflect.Method.invoke(Unknown Source)
#>  at sparklyr.Invoke.invoke(invoke.scala:139)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
#>  at java.lang.Thread.run(Unknown Source)
print(cT)
#> Error in print(cT): object 'cT' not found
#    meas val
#  1  AUC AUC
#  2   R2  R2

tab <- td %.>%
  blocks_to_rowrecs(.,
                    keyColumns = NULL,
                    controlTable = cT,
                    temporary = FALSE) %.>%
  materialize(my_db, .)
#> Error in is.data.frame(controlTable): object 'cT' not found

print(tab)
#> Error in print(tab): object 'tab' not found
#  [1] "table(`rquery_mat_62035167531946068426_0000000000`; AUC, R2)"

rstr(my_db, tab)
#> Error in "relop_table_source" %in% class(tableName): object 'tab' not found
#  table `rquery_mat_62035167531946068426_0000000000` SQLiteConnection 
#   nrow: 1 
#  'data.frame':   1 obs. of  2 variables:
#   $ AUC: num 0.6
#   $ R2 : num 0.2

if(use_spark) {
  sparklyr::spark_disconnect(my_db)
} else {
  DBI::dbDisconnect(my_db)
}
#> NULL
```

<sup>Created on 2019-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by JohnMount** [comment]
That is a known [`sparklyr` issue](https://github.com/rstudio/sparklyr/issues/1496).

The error message is saying the cluster is defective in the sense it does not have `HIVE` support set up (needed for some table materialization/persistence tasks).  On a production cluster we would take that to IT/OPS and work on it.  In this case it is: `sparklyr` started up a local demonstration cluster of its own choosing, and failed to instantiate any `HIVE` support. From a user point of view  it is a bit of a "monkey's paw" moment (the use wished for a cluster, but didn't specify enough details to prevent the curse).  So I would say the root cause is: `spakrlyr` isn't correctly supporting its own default choice of local `Spark` (`2.3.0`) correctly as it doesn't set enough configuration on the way up (giving it a directory or `URL` family to enable `HIVE`).  

The easiest way to work around this is to specify a version of `Spark` that `sparklyr` is more prepared to deal with.  For example here is the same example specifying `sparklyr` `2.2.0` (as the [likely source of the example also does](https://cran.r-project.org/web/packages/cdata/readme/README.html)).

``` r
library("cdata")
library("rquery")

use_spark <- TRUE

if(use_spark) {
  my_db <- sparklyr::spark_connect(master = "local",
                                   version = "2.2.0")
} else {
  my_db <- DBI::dbConnect(RSQLite::SQLite(),
                          ":memory:")
}



# pivot example
d <- wrapr::build_frame(
  "meas", "val" |
  "AUC" , 0.6   |
  "R2"  , 0.2   )
DBI::dbWriteTable(my_db,
                  'd',
                  d,
                  temporary = TRUE)
rstr(my_db, 'd')
#> table `d` spark_connection spark_shell_connection DBIConnection 
#>  nrow: 2 
#> 'data.frame':    2 obs. of  2 variables:
#>  $ meas: chr  "AUC" "R2"
#>  $ val : num  0.6 0.2
td <- db_td(my_db, "d")
td
#> [1] "table(`d`; meas, val)"

cT <- td %.>%
  build_pivot_control(.,
                      columnToTakeKeysFrom= 'meas',
                      columnToTakeValuesFrom= 'val') %.>%
  execute(my_db, .)

print(cT)
#>   meas val
#> 1  AUC AUC
#> 2   R2  R2

tab <- td %.>%
  blocks_to_rowrecs(.,
                    keyColumns = NULL,
                    controlTable = cT,
                    temporary = FALSE) %.>%
  materialize(my_db, .)

print(tab)
#> [1] "table(`rquery_mat_63702712319116539366_0000000000`; AUC, R2)"

rstr(my_db, tab)
#> table `rquery_mat_63702712319116539366_0000000000` spark_connection spark_shell_connection DBIConnection 
#>  nrow: 1 
#> 'data.frame':    1 obs. of  2 variables:
#>  $ AUC: num 0.6
#>  $ R2 : num 0.2

if(use_spark) {
  sparklyr::spark_disconnect(my_db)
} else {
  DBI::dbDisconnect(my_db)
}
```
